Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -11,3 +11,6 @@ jobs:
 
      - name: Run a sample github actions
        run: echo "this wrkflow run successfully"
+
+     - name: Simulating error
+       run: echo "error taking place"; exit 1
